// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/sum.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberRequest) Reset() {
	*x = NumberRequest{}
	mi := &file_proto_sum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRequest) ProtoMessage() {}

func (x *NumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRequest.ProtoReflect.Descriptor instead.
func (*NumberRequest) Descriptor() ([]byte, []int) {
	return file_proto_sum_proto_rawDescGZIP(), []int{0}
}

func (x *NumberRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type NumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberResponse) Reset() {
	*x = NumberResponse{}
	mi := &file_proto_sum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberResponse) ProtoMessage() {}

func (x *NumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberResponse.ProtoReflect.Descriptor instead.
func (*NumberResponse) Descriptor() ([]byte, []int) {
	return file_proto_sum_proto_rawDescGZIP(), []int{1}
}

func (x *NumberResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_sum_proto protoreflect.FileDescriptor

const file_proto_sum_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/sum.proto\x12\x03sum\"'\n" +
	"\rNumberRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\"&\n" +
	"\x0eNumberResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total2G\n" +
	"\n" +
	"SumService\x129\n" +
	"\n" +
	"AddNumbers\x12\x12.sum.NumberRequest\x1a\x13.sum.NumberResponse(\x010\x01B$Z\"grpc-bidi-addition/pkg/proto;protob\x06proto3"

var (
	file_proto_sum_proto_rawDescOnce sync.Once
	file_proto_sum_proto_rawDescData []byte
)

func file_proto_sum_proto_rawDescGZIP() []byte {
	file_proto_sum_proto_rawDescOnce.Do(func() {
		file_proto_sum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sum_proto_rawDesc), len(file_proto_sum_proto_rawDesc)))
	})
	return file_proto_sum_proto_rawDescData
}

var file_proto_sum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sum_proto_goTypes = []any{
	(*NumberRequest)(nil),  // 0: sum.NumberRequest
	(*NumberResponse)(nil), // 1: sum.NumberResponse
}
var file_proto_sum_proto_depIdxs = []int32{
	0, // 0: sum.SumService.AddNumbers:input_type -> sum.NumberRequest
	1, // 1: sum.SumService.AddNumbers:output_type -> sum.NumberResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sum_proto_init() }
func file_proto_sum_proto_init() {
	if File_proto_sum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sum_proto_rawDesc), len(file_proto_sum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sum_proto_goTypes,
		DependencyIndexes: file_proto_sum_proto_depIdxs,
		MessageInfos:      file_proto_sum_proto_msgTypes,
	}.Build()
	File_proto_sum_proto = out.File
	file_proto_sum_proto_goTypes = nil
	file_proto_sum_proto_depIdxs = nil
}
